#############################################################################
# Makefile for building: menuwindow
# Generated by qmake (2.01a) (Qt 4.5.3) on: Wed Apr 10 10:31:57 2013
# Project:  menuwindow.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/qmake -spec /usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qws/linux-arm-g++ -unix -o Makefile menuwindow.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-gcc
CXX           = /usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.5.3-arm/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.5.3-arm/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.5.3-arm/include/QtGui -I/usr/local/Trolltech/QtEmbedded-4.5.3-arm/include/QtSql -I/usr/local/Trolltech/QtEmbedded-4.5.3-arm/include -I.
LINK          = /usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib -lQtSql -L/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib -lQtGui -lQtNetwork -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = /usr/local/arm/4.2.2-eabi/usr/bin/arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		menuwindow.cpp \
		aboutdialog.cpp \
		historydialog.cpp \
		timesetdialog.cpp \
		hostsetdialog.cpp \
		bussetdialog.cpp \
		combodelegate.cpp \
		spindelegate.cpp \
		unitsetdialog.cpp \
		netsetdialog.cpp \
		serialtestdialog.cpp \
		soundtestdialog.cpp \
		singletestdialog.cpp \
		nettestdialog.cpp \
		type.cpp \
		database.cpp \
		boardregthread.cpp \
		boardregdialog.cpp \
		pollingthread.cpp \
		mainwidget.cpp \
		nodeid.cpp \
		keydetect.cpp \
		zzlinksetwidget.cpp \
		zdlinksetwidget.cpp \
		linkdialog.cpp \
		link.cpp \
		dzlinksetwidget.cpp \
		ddlinksetwidget.cpp \
		passworddialog.cpp \
		viewmenuwindow.cpp \
		eventdialog.cpp \
		reginfodialog.cpp \
		printerdialog.cpp \
		serial.cpp \
		groupsetdialog.cpp \
		operationhis.cpp \
		shieldwidget.cpp \
		handwidget.cpp \
		public.cpp moc_menuwindow.cpp \
		moc_aboutdialog.cpp \
		moc_historydialog.cpp \
		moc_timesetdialog.cpp \
		moc_hostsetdialog.cpp \
		moc_bussetdialog.cpp \
		moc_combodelegate.cpp \
		moc_spindelegate.cpp \
		moc_unitsetdialog.cpp \
		moc_netsetdialog.cpp \
		moc_serialtestdialog.cpp \
		moc_soundtestdialog.cpp \
		moc_singletestdialog.cpp \
		moc_nettestdialog.cpp \
		moc_boardregthread.cpp \
		moc_boardregdialog.cpp \
		moc_pollingthread.cpp \
		moc_mainwidget.cpp \
		moc_keydetect.cpp \
		moc_zzlinksetwidget.cpp \
		moc_zdlinksetwidget.cpp \
		moc_linkdialog.cpp \
		moc_link.cpp \
		moc_dzlinksetwidget.cpp \
		moc_ddlinksetwidget.cpp \
		moc_passworddialog.cpp \
		moc_viewmenuwindow.cpp \
		moc_eventdialog.cpp \
		moc_reginfodialog.cpp \
		moc_printerdialog.cpp \
		moc_groupsetdialog.cpp \
		moc_operationhis.cpp \
		moc_shieldwidget.cpp \
		moc_handwidget.cpp \
		qrc_menuwindow.cpp
OBJECTS       = main.o \
		menuwindow.o \
		aboutdialog.o \
		historydialog.o \
		timesetdialog.o \
		hostsetdialog.o \
		bussetdialog.o \
		combodelegate.o \
		spindelegate.o \
		unitsetdialog.o \
		netsetdialog.o \
		serialtestdialog.o \
		soundtestdialog.o \
		singletestdialog.o \
		nettestdialog.o \
		type.o \
		database.o \
		boardregthread.o \
		boardregdialog.o \
		pollingthread.o \
		mainwidget.o \
		nodeid.o \
		keydetect.o \
		zzlinksetwidget.o \
		zdlinksetwidget.o \
		linkdialog.o \
		link.o \
		dzlinksetwidget.o \
		ddlinksetwidget.o \
		passworddialog.o \
		viewmenuwindow.o \
		eventdialog.o \
		reginfodialog.o \
		printerdialog.o \
		serial.o \
		groupsetdialog.o \
		operationhis.o \
		shieldwidget.o \
		handwidget.o \
		public.o \
		moc_menuwindow.o \
		moc_aboutdialog.o \
		moc_historydialog.o \
		moc_timesetdialog.o \
		moc_hostsetdialog.o \
		moc_bussetdialog.o \
		moc_combodelegate.o \
		moc_spindelegate.o \
		moc_unitsetdialog.o \
		moc_netsetdialog.o \
		moc_serialtestdialog.o \
		moc_soundtestdialog.o \
		moc_singletestdialog.o \
		moc_nettestdialog.o \
		moc_boardregthread.o \
		moc_boardregdialog.o \
		moc_pollingthread.o \
		moc_mainwidget.o \
		moc_keydetect.o \
		moc_zzlinksetwidget.o \
		moc_zdlinksetwidget.o \
		moc_linkdialog.o \
		moc_link.o \
		moc_dzlinksetwidget.o \
		moc_ddlinksetwidget.o \
		moc_passworddialog.o \
		moc_viewmenuwindow.o \
		moc_eventdialog.o \
		moc_reginfodialog.o \
		moc_printerdialog.o \
		moc_groupsetdialog.o \
		moc_operationhis.o \
		moc_shieldwidget.o \
		moc_handwidget.o \
		qrc_menuwindow.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/include_source_dir.prf \
		menuwindow.pro
QMAKE_TARGET  = menuwindow
DESTDIR       = 
TARGET        = menuwindow

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: menuwindow.pro  /usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/g++.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtSql.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtCore.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qws/linux-arm-g++ -unix -o Makefile menuwindow.pro
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/g++.conf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtSql.prl:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtCore.prl:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.5.3-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.5.3-arm/mkspecs/qws/linux-arm-g++ -unix -o Makefile menuwindow.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/menuwindow1.0.0 || $(MKDIR) .tmp/menuwindow1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/menuwindow1.0.0/ && $(COPY_FILE) --parents menuwindow.h aboutdialog.h historydialog.h timesetdialog.h hostsetdialog.h bussetdialog.h combodelegate.h spindelegate.h unitsetdialog.h netsetdialog.h serialtestdialog.h soundtestdialog.h singletestdialog.h nettestdialog.h canframe.h info.h type.h database.h boardregthread.h boardregdialog.h defMacro.h pollingthread.h mainwidget.h nodeid.h keydetect.h ch452.h zzlinksetwidget.h zdlinksetwidget.h linkdialog.h link.h dzlinksetwidget.h ddlinksetwidget.h pic16f676.h passworddialog.h viewmenuwindow.h eventdialog.h reginfodialog.h printerdialog.h serial.h groupsetdialog.h operationhis.h shieldwidget.h handwidget.h public.h .tmp/menuwindow1.0.0/ && $(COPY_FILE) --parents menuwindow.qrc .tmp/menuwindow1.0.0/ && $(COPY_FILE) --parents main.cpp menuwindow.cpp aboutdialog.cpp historydialog.cpp timesetdialog.cpp hostsetdialog.cpp bussetdialog.cpp combodelegate.cpp spindelegate.cpp unitsetdialog.cpp netsetdialog.cpp serialtestdialog.cpp soundtestdialog.cpp singletestdialog.cpp nettestdialog.cpp type.cpp database.cpp boardregthread.cpp boardregdialog.cpp pollingthread.cpp mainwidget.cpp nodeid.cpp keydetect.cpp zzlinksetwidget.cpp zdlinksetwidget.cpp linkdialog.cpp link.cpp dzlinksetwidget.cpp ddlinksetwidget.cpp passworddialog.cpp viewmenuwindow.cpp eventdialog.cpp reginfodialog.cpp printerdialog.cpp serial.cpp groupsetdialog.cpp operationhis.cpp shieldwidget.cpp handwidget.cpp public.cpp .tmp/menuwindow1.0.0/ && (cd `dirname .tmp/menuwindow1.0.0` && $(TAR) menuwindow1.0.0.tar menuwindow1.0.0 && $(COMPRESS) menuwindow1.0.0.tar) && $(MOVE) `dirname .tmp/menuwindow1.0.0`/menuwindow1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/menuwindow1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_menuwindow.cpp moc_aboutdialog.cpp moc_historydialog.cpp moc_timesetdialog.cpp moc_hostsetdialog.cpp moc_bussetdialog.cpp moc_combodelegate.cpp moc_spindelegate.cpp moc_unitsetdialog.cpp moc_netsetdialog.cpp moc_serialtestdialog.cpp moc_soundtestdialog.cpp moc_singletestdialog.cpp moc_nettestdialog.cpp moc_boardregthread.cpp moc_boardregdialog.cpp moc_pollingthread.cpp moc_mainwidget.cpp moc_keydetect.cpp moc_zzlinksetwidget.cpp moc_zdlinksetwidget.cpp moc_linkdialog.cpp moc_link.cpp moc_dzlinksetwidget.cpp moc_ddlinksetwidget.cpp moc_passworddialog.cpp moc_viewmenuwindow.cpp moc_eventdialog.cpp moc_reginfodialog.cpp moc_printerdialog.cpp moc_groupsetdialog.cpp moc_operationhis.cpp moc_shieldwidget.cpp moc_handwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_menuwindow.cpp moc_aboutdialog.cpp moc_historydialog.cpp moc_timesetdialog.cpp moc_hostsetdialog.cpp moc_bussetdialog.cpp moc_combodelegate.cpp moc_spindelegate.cpp moc_unitsetdialog.cpp moc_netsetdialog.cpp moc_serialtestdialog.cpp moc_soundtestdialog.cpp moc_singletestdialog.cpp moc_nettestdialog.cpp moc_boardregthread.cpp moc_boardregdialog.cpp moc_pollingthread.cpp moc_mainwidget.cpp moc_keydetect.cpp moc_zzlinksetwidget.cpp moc_zdlinksetwidget.cpp moc_linkdialog.cpp moc_link.cpp moc_dzlinksetwidget.cpp moc_ddlinksetwidget.cpp moc_passworddialog.cpp moc_viewmenuwindow.cpp moc_eventdialog.cpp moc_reginfodialog.cpp moc_printerdialog.cpp moc_groupsetdialog.cpp moc_operationhis.cpp moc_shieldwidget.cpp moc_handwidget.cpp
moc_menuwindow.cpp: printerdialog.h \
		menuwindow.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) menuwindow.h -o moc_menuwindow.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_historydialog.cpp: historydialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) historydialog.h -o moc_historydialog.cpp

moc_timesetdialog.cpp: timesetdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) timesetdialog.h -o moc_timesetdialog.cpp

moc_hostsetdialog.cpp: hostsetdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) hostsetdialog.h -o moc_hostsetdialog.cpp

moc_bussetdialog.cpp: bussetdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) bussetdialog.h -o moc_bussetdialog.cpp

moc_combodelegate.cpp: combodelegate.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) combodelegate.h -o moc_combodelegate.cpp

moc_spindelegate.cpp: spindelegate.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) spindelegate.h -o moc_spindelegate.cpp

moc_unitsetdialog.cpp: unitsetdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) unitsetdialog.h -o moc_unitsetdialog.cpp

moc_netsetdialog.cpp: netsetdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) netsetdialog.h -o moc_netsetdialog.cpp

moc_serialtestdialog.cpp: serialtestdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) serialtestdialog.h -o moc_serialtestdialog.cpp

moc_soundtestdialog.cpp: soundtestdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) soundtestdialog.h -o moc_soundtestdialog.cpp

moc_singletestdialog.cpp: singletestdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) singletestdialog.h -o moc_singletestdialog.cpp

moc_nettestdialog.cpp: nettestdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) nettestdialog.h -o moc_nettestdialog.cpp

moc_boardregthread.cpp: canframe.h \
		defMacro.h \
		boardregthread.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) boardregthread.h -o moc_boardregthread.cpp

moc_boardregdialog.cpp: boardregdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) boardregdialog.h -o moc_boardregdialog.cpp

moc_pollingthread.cpp: canframe.h \
		defMacro.h \
		nodeid.h \
		pollingthread.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) pollingthread.h -o moc_pollingthread.cpp

moc_mainwidget.cpp: nodeid.h \
		mainwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_keydetect.cpp: canframe.h \
		keydetect.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) keydetect.h -o moc_keydetect.cpp

moc_zzlinksetwidget.cpp: zzlinksetwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) zzlinksetwidget.h -o moc_zzlinksetwidget.cpp

moc_zdlinksetwidget.cpp: zdlinksetwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) zdlinksetwidget.h -o moc_zdlinksetwidget.cpp

moc_linkdialog.cpp: linkdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) linkdialog.h -o moc_linkdialog.cpp

moc_link.cpp: link.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) link.h -o moc_link.cpp

moc_dzlinksetwidget.cpp: dzlinksetwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) dzlinksetwidget.h -o moc_dzlinksetwidget.cpp

moc_ddlinksetwidget.cpp: ddlinksetwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) ddlinksetwidget.h -o moc_ddlinksetwidget.cpp

moc_passworddialog.cpp: passworddialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) passworddialog.h -o moc_passworddialog.cpp

moc_viewmenuwindow.cpp: viewmenuwindow.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) viewmenuwindow.h -o moc_viewmenuwindow.cpp

moc_eventdialog.cpp: eventdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) eventdialog.h -o moc_eventdialog.cpp

moc_reginfodialog.cpp: reginfodialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) reginfodialog.h -o moc_reginfodialog.cpp

moc_printerdialog.cpp: printerdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) printerdialog.h -o moc_printerdialog.cpp

moc_groupsetdialog.cpp: groupsetdialog.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) groupsetdialog.h -o moc_groupsetdialog.cpp

moc_operationhis.cpp: operationhis.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) operationhis.h -o moc_operationhis.cpp

moc_shieldwidget.cpp: shieldwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) shieldwidget.h -o moc_shieldwidget.cpp

moc_handwidget.cpp: handwidget.h
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/moc $(DEFINES) $(INCPATH) handwidget.h -o moc_handwidget.cpp

compiler_rcc_make_all: qrc_menuwindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_menuwindow.cpp
qrc_menuwindow.cpp: menuwindow.qrc \
		background.PNG \
		start.png \
		black.PNG \
		white.PNG
	/usr/local/Trolltech/QtEmbedded-4.5.3-arm/bin/rcc -name menuwindow menuwindow.qrc -o qrc_menuwindow.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwidget.h \
		nodeid.h \
		database.h \
		operationhis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

menuwindow.o: menuwindow.cpp menuwindow.h \
		printerdialog.h \
		timesetdialog.h \
		hostsetdialog.h \
		unitsetdialog.h \
		bussetdialog.h \
		netsetdialog.h \
		serialtestdialog.h \
		linkdialog.h \
		soundtestdialog.h \
		singletestdialog.h \
		nettestdialog.h \
		link.h \
		operationhis.h \
		shieldwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menuwindow.o menuwindow.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

historydialog.o: historydialog.cpp historydialog.h \
		type.h \
		serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historydialog.o historydialog.cpp

timesetdialog.o: timesetdialog.cpp timesetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesetdialog.o timesetdialog.cpp

hostsetdialog.o: hostsetdialog.cpp hostsetdialog.h \
		serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hostsetdialog.o hostsetdialog.cpp

bussetdialog.o: bussetdialog.cpp bussetdialog.h \
		type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bussetdialog.o bussetdialog.cpp

combodelegate.o: combodelegate.cpp combodelegate.h \
		info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o combodelegate.o combodelegate.cpp

spindelegate.o: spindelegate.cpp spindelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spindelegate.o spindelegate.cpp

unitsetdialog.o: unitsetdialog.cpp unitsetdialog.h \
		combodelegate.h \
		spindelegate.h \
		info.h \
		type.h \
		groupsetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unitsetdialog.o unitsetdialog.cpp

netsetdialog.o: netsetdialog.cpp netsetdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netsetdialog.o netsetdialog.cpp

serialtestdialog.o: serialtestdialog.cpp serialtestdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialtestdialog.o serialtestdialog.cpp

soundtestdialog.o: soundtestdialog.cpp soundtestdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundtestdialog.o soundtestdialog.cpp

singletestdialog.o: singletestdialog.cpp singletestdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o singletestdialog.o singletestdialog.cpp

nettestdialog.o: nettestdialog.cpp nettestdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nettestdialog.o nettestdialog.cpp

type.o: type.cpp type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o type.o type.cpp

database.o: database.cpp database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

boardregthread.o: boardregthread.cpp boardregthread.h \
		canframe.h \
		defMacro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boardregthread.o boardregthread.cpp

boardregdialog.o: boardregdialog.cpp boardregdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boardregdialog.o boardregdialog.cpp

pollingthread.o: pollingthread.cpp pollingthread.h \
		canframe.h \
		defMacro.h \
		nodeid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pollingthread.o pollingthread.cpp

mainwidget.o: mainwidget.cpp boardregdialog.h \
		pollingthread.h \
		canframe.h \
		defMacro.h \
		nodeid.h \
		boardregthread.h \
		menuwindow.h \
		printerdialog.h \
		viewmenuwindow.h \
		mainwidget.h \
		type.h \
		ch452.h \
		keydetect.h \
		pic16f676.h \
		passworddialog.h \
		serial.h \
		eventdialog.h \
		operationhis.h \
		handwidget.h \
		shieldwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

nodeid.o: nodeid.cpp nodeid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodeid.o nodeid.cpp

keydetect.o: keydetect.cpp keydetect.h \
		canframe.h \
		ch452.h \
		pic16f676.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keydetect.o keydetect.cpp

zzlinksetwidget.o: zzlinksetwidget.cpp info.h \
		type.h \
		zzlinksetwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zzlinksetwidget.o zzlinksetwidget.cpp

zdlinksetwidget.o: zdlinksetwidget.cpp info.h \
		type.h \
		zdlinksetwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zdlinksetwidget.o zdlinksetwidget.cpp

linkdialog.o: linkdialog.cpp linkdialog.h \
		ddlinksetwidget.h \
		dzlinksetwidget.h \
		zdlinksetwidget.h \
		zzlinksetwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linkdialog.o linkdialog.cpp

link.o: link.cpp canframe.h \
		link.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o link.o link.cpp

dzlinksetwidget.o: dzlinksetwidget.cpp dzlinksetwidget.h \
		info.h \
		type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dzlinksetwidget.o dzlinksetwidget.cpp

ddlinksetwidget.o: ddlinksetwidget.cpp linkdialog.h \
		ddlinksetwidget.h \
		info.h \
		type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ddlinksetwidget.o ddlinksetwidget.cpp

passworddialog.o: passworddialog.cpp passworddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passworddialog.o passworddialog.cpp

viewmenuwindow.o: viewmenuwindow.cpp viewmenuwindow.h \
		aboutdialog.h \
		historydialog.h \
		unitsetdialog.h \
		bussetdialog.h \
		netsetdialog.h \
		linkdialog.h \
		passworddialog.h \
		reginfodialog.h \
		operationhis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewmenuwindow.o viewmenuwindow.cpp

eventdialog.o: eventdialog.cpp type.h \
		defMacro.h \
		eventdialog.h \
		handwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventdialog.o eventdialog.cpp

reginfodialog.o: reginfodialog.cpp reginfodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reginfodialog.o reginfodialog.cpp

printerdialog.o: printerdialog.cpp printerdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printerdialog.o printerdialog.cpp

serial.o: serial.cpp serial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial.o serial.cpp

groupsetdialog.o: groupsetdialog.cpp groupsetdialog.h \
		info.h \
		type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupsetdialog.o groupsetdialog.cpp

operationhis.o: operationhis.cpp operationhis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operationhis.o operationhis.cpp

shieldwidget.o: shieldwidget.cpp shieldwidget.h \
		info.h \
		type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shieldwidget.o shieldwidget.cpp

handwidget.o: handwidget.cpp handwidget.h \
		info.h \
		type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o handwidget.o handwidget.cpp

public.o: public.cpp public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o public.o public.cpp

moc_menuwindow.o: moc_menuwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menuwindow.o moc_menuwindow.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_historydialog.o: moc_historydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_historydialog.o moc_historydialog.cpp

moc_timesetdialog.o: moc_timesetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timesetdialog.o moc_timesetdialog.cpp

moc_hostsetdialog.o: moc_hostsetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hostsetdialog.o moc_hostsetdialog.cpp

moc_bussetdialog.o: moc_bussetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bussetdialog.o moc_bussetdialog.cpp

moc_combodelegate.o: moc_combodelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_combodelegate.o moc_combodelegate.cpp

moc_spindelegate.o: moc_spindelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spindelegate.o moc_spindelegate.cpp

moc_unitsetdialog.o: moc_unitsetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unitsetdialog.o moc_unitsetdialog.cpp

moc_netsetdialog.o: moc_netsetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_netsetdialog.o moc_netsetdialog.cpp

moc_serialtestdialog.o: moc_serialtestdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialtestdialog.o moc_serialtestdialog.cpp

moc_soundtestdialog.o: moc_soundtestdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundtestdialog.o moc_soundtestdialog.cpp

moc_singletestdialog.o: moc_singletestdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_singletestdialog.o moc_singletestdialog.cpp

moc_nettestdialog.o: moc_nettestdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nettestdialog.o moc_nettestdialog.cpp

moc_boardregthread.o: moc_boardregthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boardregthread.o moc_boardregthread.cpp

moc_boardregdialog.o: moc_boardregdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boardregdialog.o moc_boardregdialog.cpp

moc_pollingthread.o: moc_pollingthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pollingthread.o moc_pollingthread.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_keydetect.o: moc_keydetect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keydetect.o moc_keydetect.cpp

moc_zzlinksetwidget.o: moc_zzlinksetwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zzlinksetwidget.o moc_zzlinksetwidget.cpp

moc_zdlinksetwidget.o: moc_zdlinksetwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zdlinksetwidget.o moc_zdlinksetwidget.cpp

moc_linkdialog.o: moc_linkdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_linkdialog.o moc_linkdialog.cpp

moc_link.o: moc_link.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_link.o moc_link.cpp

moc_dzlinksetwidget.o: moc_dzlinksetwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dzlinksetwidget.o moc_dzlinksetwidget.cpp

moc_ddlinksetwidget.o: moc_ddlinksetwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ddlinksetwidget.o moc_ddlinksetwidget.cpp

moc_passworddialog.o: moc_passworddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passworddialog.o moc_passworddialog.cpp

moc_viewmenuwindow.o: moc_viewmenuwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewmenuwindow.o moc_viewmenuwindow.cpp

moc_eventdialog.o: moc_eventdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventdialog.o moc_eventdialog.cpp

moc_reginfodialog.o: moc_reginfodialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reginfodialog.o moc_reginfodialog.cpp

moc_printerdialog.o: moc_printerdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_printerdialog.o moc_printerdialog.cpp

moc_groupsetdialog.o: moc_groupsetdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_groupsetdialog.o moc_groupsetdialog.cpp

moc_operationhis.o: moc_operationhis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_operationhis.o moc_operationhis.cpp

moc_shieldwidget.o: moc_shieldwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_shieldwidget.o moc_shieldwidget.cpp

moc_handwidget.o: moc_handwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_handwidget.o moc_handwidget.cpp

qrc_menuwindow.o: qrc_menuwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_menuwindow.o qrc_menuwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

